<?php

return [
    'admin_404' => 'templates/admin/images/404.png',
    'userDefault' => false,
    'paginate' => 5,
    'slider_number' => 3,
    'banner' => 4,
    'skip1' => 1,
    'skip2' => 2,
    'skip3' => 3,
    'product_picture_default' => 'templates/ecommerce/images/default-image.jpg',
    'file_upload' => 'templates/upload/',
    'topSell' => 6,
    'rate' => 5,
    'rate_start' => 0,
    'strlimit30' => 30,
    'top' => 3,
    'star5' => 5,
    'star4' => 4,
    'star3' => 3,
    'parent_category' => 0,
    'num10' => 10,
    'num20' => 20,
    'num30' => 30,
    'grid' => 'grid',
    'list' => 'list',
    'num0' => 0,
    'num1' => 1,
    'paginate_review' => 2,
    'paginate_comment' => 4,
    'paginate_admin' => 10,
    'fileUpload' => 'templates/ecommerce/images/product/',
    'true' => true,
    'false' => false,
    'direct' => 'direct',
    'status_default' => 0,
    'fileUpload' => 'templates/ecommerce/images/product/',
    'processing' => 0,
    'delivering' => 1,
    'closed' => 2,
];
